name: pytorch_p36_clean_cuda
channels:
  - pytorch
  - conda-forge
  - defaults
  - numba
  - soumith
dependencies:
  - bleach=2.0.0
  - decorator=4.1.2
  - entrypoints=0.2.3
  - gmp=6.1.2
  - html5lib=1.0.1
  - ipykernel=4.8.2
  - ipython=6.2.1
  - ipython_genutils=0.2.0
  - jedi=0.11.1
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter_client=5.2.2
  - jupyter_core=4.4.0
  - libsodium=1.0.15
  - markupsafe=1.0
  - mistune=0.8.3
  - nb_conda=2.2.1
  - nb_conda_kernels=2.1.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.4.0
#  - pandoc=2.1.1
#  - pandocfilters=1.4.1
  - parso=0.1.1
  - pexpect=4.4.0
  - pickleshare=0.7.4
  - prompt_toolkit=1.0.15
  - protobuf=3.5.0
  - ptyprocess=0.5.2
  - pygments=2.2.0
  - python-dateutil=2.6.1
  - pyzmq=17.0.0
  - send2trash=1.5.0
  - simplegeneric=0.8.1
  - six=1.11.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tornado=4.5.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5
  - zeromq=4.2.3
  - asn1crypto=0.24.0
  - autovizwidget=0.12.5
  - bokeh=0.12.14
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - certifi=2018.4.16
  - cffi=1.11.4
  - chardet=3.0.4
  - cryptography=2.1.4
  - cycler=0.10.0
  - dbus=1.13.2
  - expat=2.2.5
  - fontconfig=2.12.4
  - freetype=2.8
  - glib=2.53.6
  - graphite2=1.3.10
  - graphviz=2.40.1
  - gst-plugins-base=1.12.4
  - gstreamer=1.12.4
  - h5py=2.7.1
  - harfbuzz=1.7.4
  - hdf5=1.10.1
  - hdijupyterutils=0.12.5
  - icu=58.2
  - idna=2.6
  - intel-openmp=2018.0.0
  - ipywidgets=7.1.2
  - jpeg=9b
  - kiwisolver=1.0.1
  - krb5=1.14.2
  - libedit=3.1
  - libffi=3.2.1
#  - libgcc-ng=7.3.0
  - libgfortran-ng=7.2.0
  - libpng=1.6.34
#  - libstdcxx-ng>=7.2.0
  - libtiff=4.0.9
  - libtool=2.4.6
  - libxcb=1.12
  - libxml2=2.9.7
  - matplotlib=2.2.2
#  - mkl>=2018.0.1
#  - ncurses=6.0
  - numpy=1.14.1
  - olefile=0.45.1
  - openjdk=8.0.121
  - openssl=1.0.2o
  - packaging=16.8
  - pandas=0.22.0
  - pango=1.41.0
  - patsy=0.5.0
  - pcre=8.41
  - pillow=5.0.0
  - pip=9.0.1
  - pixman=0.34.0
  - plotly=2.4.0
  - pycparser=2.18
  - pykerberos=1.1.14
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
#  - pyqt=5.6.0
  - pysocks=1.6.7
  - python=3.6.4
  - pytz=2018.3
  - pyyaml=3.12
#  - qt=5.6.2
#  - readline=7.0
  - requests=2.18.4
  - requests-kerberos=0.11.0
  - scipy=1.0.0
  - seaborn=0.8.1
  - setuptools=38.5.1
  - sip=4.18.1
  - sparkmagic=0.12.5
#  - sqlite>=3.22.0
  - statsmodels=0.8.0
#  - tk=8.6.7
  - urllib3=1.22
  - wheel=0.30.0
  - widgetsnbextension=3.1.4
#  - xz=5.2.3
  - yaml=0.1.7
#  - zlib=1.2.11
  - cuda90=1.0
  - pytorch=0.3.1=py36_cuda9.0.176_cudnn7.0.5_2
#  - torchvision=0.2.0
  - pip:
    - boto3==1.5.34
    - botocore==1.8.48
    - docutils==0.14
    - environment-kernels==1.1.1
    - jmespath==0.9.3
    - psycopg2==2.7.4
    - py4j==0.10.4
    - pygal==2.4.0
    - pyspark==2.2.1
    - s3transfer==0.1.13
    - sqlalchemy==1.2.3
    - torch==0.3.1.post2
 #   - transformer==0.0.0

